<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="descripcion" content="Pagina interactiva de enseñanza" />
	<meta name="Keywords" content= "Balance ecuaciones, Reacciones, Caida libre" />
	<title>Fragancias y Perfumes Escencial</title>
	<link href="EstiloLogin.css" rel="stylesheet" type="text/css" media="screen" />
	<script type="text/javascript" src="Balance.js"></script>
</head>
<body>
	<form name="contactform" method="POST" action="Validar_User.php"> 
	<h2>Ingreso de usuarios </h2>
    <input  type="email" name="Correo"  class='form-control' placeholder="&#x2709;  Ingrese Correo Electronico" required="required" >
    <input  type="password" class='form-control' name="ContraseIN" placeholder="&#128272;Contraseña" required="required" >
    <input type="submit" name="ingresar" class='btn btn-primary btn-block' id="enviar" value="Ingresar">
    </form>
</body>

</html>